name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku container registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Check if Heroku app exists
        id: check_app
        run: |
          if heroku apps:info citadle-frontend > /dev/null 2>&1; then
              echo "App exists"
              echo "::set-output name=exists::true"
          else
              echo "App does not exist"
              echo "::set-output name=exists::false"
          fi
        env:
          HEROKU_APP_NAME: citadle-frontend
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Create Heroku app
        if: steps.check_app.outputs.exists == 'false'
        run: heroku create citadle-frontend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build Docker image
        run: docker build -t registry.heroku.com/citadle-frontend/web .

      - name: Push Docker image to Heroku container registry
        run: docker push registry.heroku.com/citadle-frontend/web

      - name: Set environment variables
        run: |
          heroku config:set \
          VITE_API_URL=${{ secrets.API_URL }} \
          VITE_API_KEY=${{ secrets.API_KEY }} \
          --app citadle-frontend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release Docker image to Heroku
        run: heroku container:release web --app citadle-frontend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
